[profile.default]
src = "src"
out = "out"
libs = ["lib"]
test = 'test'
ffi = true
auto_detect_solc = false
evm_version = 'cancun'
ignored_error_codes = [2394] # Transient storage
fs_permissions = [
    { access = "read-write", path = "./" },
] # SE-2 default to allow script to write contract info from /foundry to /nextjs


# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
